export const USER_CREATED = "USER_CREATED";
export const USER_AUTENTICATED = "USER_AUTENTICATED";

export const LOGIN_ERROR = "USER_ERROR";
export const SIGN_OFF_USER = "SIGN_OFF_USER";
export const GET_USER = "GET_USER";
export const EDIT_USER_INFO = "EDIT_USER_INFO";
export const DELETE_USER = "DELETE_USER";

export const GET_USER_ORDERS = "GET_USER_ORDERS";

export const GET_USER_PAYMENTS = "GET_USER_PAYMENTS";
export const CREATE_USER_PAYMENT = "CREATE_USER_PAYMENT";
export const EDIT_USER_PAYMENT = "EDIT_USER_PAYMENT";
export const DELETE_USER_PAYMENT = "DELETE_USER_PAYMENT";  