export const USER_CREATED = "USER_CREATED";
export const USER_AUTENTICATED = "USER_AUTENTICATED";

export const LOGIN_ERROR = "USER_ERROR";
export const SIGN_OFF_USER = "SIGN_OFF_USER";
export const GET_USER = "GET_USER";
export const EDIT_USER_INFO = "EDIT_USER_INFO";
export const DELETE_USER = "DELETE_USER";

export const GET_USER_ORDERS = "GET_USER_ORDERS";
export const CREATE_USER_ORDER = "CREATE_USER_ORDER"
export const EDIT_ORDER = "EDIT_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";

export const GET_USER_PAYMENTS = "GET_USER_PAYMENTS";
export const CREATE_USER_PAYMENT = "CREATE_USER_PAYMENT";
export const EDIT_USER_PAYMENT = "EDIT_USER_PAYMENT";
export const DELETE_USER_PAYMENT = "DELETE_USER_PAYMENT";  

export const GET_ADDRESS = "GET_ADDRESS";
export const CREATE_ADDRESS = "CREATE_ADDRESS";
export const EDIT_ADDRESS= "EDIT_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";